var users = [{
    name       : 'Maria Posoda',
    phone      : '0123456',
    email      : 'maria@example.com',
    img        : 'https://i.ibb.co/G7dQyNW/wild-11-904294440.jpg',
    profession : 'Teacher',
    salary     : 25000,
},
{
    name       : 'Karim',
    phone      : '0123456',
    email      : 'karim@example.com',
    img        : 'https://i.ibb.co/3sTw36b/wild-10-708885142.jpg',
    profession : 'Doctor',
    salary     : 35000,
},
{
    name       : 'Rahim',
    phone      : '0123456',
    email      : 'rahim@example.com',
    img        : 'https://i.ibb.co/6tBBtBQ/wild-7-136263819.jpg',
    profession : 'Web deb',
    salary     : 30000,
},
{
    name       : 'Jak',
    phone      : '0123456',
    email      : 'jak@example.com',
    img        : 'https://i.ibb.co/Kh7rGVH/wild-6-595721861.jpg',
    profession : 'App dev',
    salary     : 50000,
},
{
    name       : 'Jahangir',
    phone      : '0123456',
    email      : 'jahangir@example.com',
    img        : 'https://i.ibb.co/hfXss8n/wild-5-815788208.jpg',
    profession : 'It expart',
    salary     : 25000,
},
{
    name       : 'Bappy',
    phone      : '0123456',
    email      : 'bappy@example.com',
    img        : 'https://i.ibb.co/2nrYRyH/Truly-Amazing-Best-Nature-Photography-17.jpg',
    profession : 'Vlogger',
    salary     : 25000,
},
{
    name       : 'Nipun',
    phone      : '0123456',
    email      : 'nipuna@example.com',
    img        : 'https://i.ibb.co/q0q3b9q/Truly-Amazing-Best-Nature-Photography-16.jpg',
    profession : 'Traveller',
    salary     : 25000,
},
{
    name       : 'Faysal',
    phone      : '0123456',
    email      : 'faysal@example.com',
    img        : 'https://i.ibb.co/2nrYRyH/Truly-Amazing-Best-Nature-Photography-17.jpg',
    profession : 'Teacher',
    salary     : 25000,
},
{
    name       : 'Mahin',
    phone      : '0123456',
    email      : 'mahin@example.com',
    img        : 'https://i.ibb.co/q0q3b9q/Truly-Amazing-Best-Nature-Photography-16.jpg',
    profession : 'Govt service holder',
    salary     : 25000,
},
{
    name       : 'Taher',
    phone      : '0123456',
    email      : 'taher@example.com',
    img        : 'https://i.ibb.co/hfWGYGR/Truly-Amazing-Best-Nature-Photography-13.jpg',
    profession : 'Business',
    salary     : 25000,
},
{
    name       : 'Hasib',
    phone      : '0123456',
    email      : 'hasib@example.com',
    img        : 'https://i.ibb.co/ZdW4026/Truly-Amazing-Best-Nature-Photography-11.jpg',
    profession : 'Shopkeeper',
    salary     : 25000,
},
{
    name       : 'Pavel',
    phone      : '0123456',
    email      : 'pavel@example.com',
    img        : 'https://i.ibb.co/S3qRR3s/Truly-Amazing-Best-Nature-Photography-9.jpg',
    profession : 'Teacher',
    salary     : 25000,
},
{
    name       : 'Himal',
    phone      : '0123456',
    email      : 'himala@example.com',
    img        : 'https://i.ibb.co/sK7kZ6f/nature-4-418376213.jpg',
    profession : 'Govt service holder',
    salary     : 25000,
},
{
    name       : 'Banna',
    phone      : '0123456',
    email      : 'banna@example.com',
    img        : 'https://i.ibb.co/fthzbB9/image-php.jpg',
    profession : 'Teacher',
    salary     : 25000,
}
];
export default users;